import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appTitle: "Kisan Ledger",
    appSubtitle: "FPO Collection Hub Companion",
    stationTag: "Station 3 · Procurement Gate",
    dashboard: "Dashboard",
    profile: "Profile",
    logout: "Logout",
    login: "Login",
    signup: "Sign Up",
    loginTab: "Login to Ledger",
    signupTab: "Quick Sign Up",
    phoneOrMemberId: "Phone Number or Member ID",
    phonePlaceholder: "e.g. 9876543210 or MH-NSK-2024-8842",
    password: "Password",
    passwordPlaceholder: "Enter your secure password",
    loginBtn: "Access Dashboard",
    signupBtn: "Create Farmer Account",
    demoCredentialsHint: "Demo Access: Use Phone 9876543210 or ID MH-NSK-2024-8842 (Password: any 4+ chars)",
    orUseOtp: "Quick SMS OTP Login",
    sendOtp: "Send OTP to Phone",
    completeProfileTitle: "Farmer Registration & Profile",
    completeProfileSubtitle: "Complete your official FPO membership details to access your produce ledger.",
    fullName: "Farmer Full Name",
    fullNamePlaceholder: "e.g. Ramesh Baburao Patil",
    memberId: "Farmer Member ID",
    memberIdPlaceholder: "e.g. MH-NSK-2024-8842",
    phoneNumber: "Registered Mobile Number",
    fpoName: "Assigned FPO Name",
    preferredLang: "Preferred Language",
    village: "Village / Gram Panchayat",
    villagePlaceholder: "e.g. Ozar Mig",
    district: "District / Tehsil",
    districtPlaceholder: "e.g. Nashik, Niphad",
    primaryCrop: "Primary Crop Delivered",
    saveProfileBtn: "Complete Profile & Enter Dashboard",
    totalProduceSold: "Total Produce Sold",
    totalNetAmount: "Total Net Amount",
    gradeWiseWeight: "Grade-wise Breakdown",
    gradeA: "Grade A (Super)",
    gradeB: "Grade B (Standard)",
    gradeC: "Grade C (Fair)",
    gradeADesc: "Premium — lowest moisture & impurities",
    gradeBDesc: "Meets procurement norms",
    gradeCDesc: "Below standard — discounted rate",
    myProduce: "My Produce Breakdown",
    soldKg: "Sold Quantity",
    earnings: "Net Earnings",
    transactionsHeading: "Transaction History",
    searchPlaceholder: "Search Transaction ID (e.g. TXN-8092)...",
    filterProduct: "Product",
    filterGrade: "Quality Grade",
    filterDate: "Date Range",
    sortBy: "Sort By",
    all: "All",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    sortNewest: "Newest First",
    sortOldest: "Oldest First",
    sortHighWeight: "Highest Weight",
    sortLowWeight: "Lowest Weight",
    sortHighAmount: "Highest Amount",
    statusConfirmed: "Confirmed",
    statusPending: "Awaiting Confirmation",
    statusIssue: "Issue Raised",
    statusLocked: "Locked",
    grossWeight: "Gross Wt",
    tareWeight: "Tare Wt",
    netWeight: "Net Weight",
    ratePerKg: "Rate / kg",
    amount: "Net Amount",
    station: "Collection Station",
    operator: "Operator ID",
    raiseIssue: "Raise Issue",
    confirmDelivery: "Confirm Delivery",
    viewDetails: "View Details",
    consignmentPhoto: "Consignment Photo",
    tamperEvident: "Tamper-Evident Photo Captured at Station Scale",
    photoUnavailable: "Consignment photo unavailable",
    raiseIssueModalTitle: "Raise an Issue with FPO",
    raiseIssueModalSubtitle: "Submit a discrepancy claim. The operator transaction remains locked and unaltered.",
    issueType: "Discrepancy Category",
    selectIssueType: "-- Select issue category --",
    issueTypeWeight: "Incorrect Weight",
    issueTypeGrade: "Incorrect Quality Grade",
    issueTypeAmount: "Incorrect Amount / Rate",
    issueTypeProduct: "Wrong Product Recorded",
    issueTypePhoto: "Consignment Photo Issue",
    issueTypeOther: "Other Discrepancy",
    issueDesc: "Describe the Issue in Detail",
    issueDescPlaceholder: "Explain what was recorded incorrectly at the weighing station scale...",
    submitIssueBtn: "Submit Issue to FPO",
    issueSubmittedSuccess: "Your issue has been submitted to the FPO for review.",
    otpModalTitle: "Farmer Delivery Confirmation (OTP)",
    otpModalSubtitle: "Enter the verification OTP sent to your registered phone",
    otpInstruction: "Enter 4-Digit Delivery OTP",
    verifyAndLockBtn: "Verify OTP & Confirm Transaction",
    otpSimulatedBanner: "Simulated SMS received on",
    otpCodeLabel: "Your verification OTP is:",
    otpSuccessMsg: "Transaction verified successfully! Record is now permanently locked.",
    lockedExplanation: "This transaction is permanently locked. To report any error, use the Raise Issue option.",
    cancel: "Cancel",
    close: "Close",
    printSlip: "Print / Save Slip",
    noTransactionsFound: "No transactions found matching your current filter criteria."
  },
  hi: {
    appTitle: "किसान लेजर",
    appSubtitle: "एफपीओ खरीद केंद्र — किसान साथी",
    stationTag: "स्टेशन 3 · खरीद गेट",
    dashboard: "डैशबोर्ड",
    profile: "प्रोफ़ाइल",
    logout: "लॉग आउट",
    login: "लॉग इन",
    signup: "साइन अप",
    loginTab: "लेजर में लॉग इन करें",
    signupTab: "त्वरित साइन अप",
    phoneOrMemberId: "मोबाइल नंबर या सदस्य आईडी",
    phonePlaceholder: "उदा. 9876543210 या MH-NSK-2024-8842",
    password: "पासवर्ड",
    passwordPlaceholder: "अपना पासवर्ड दर्ज करें",
    loginBtn: "डैशबोर्ड खोलें",
    signupBtn: "नया किसान खाता बनाएं",
    demoCredentialsHint: "डेमो खाता: मोबाइल 9876543210 या आईडी MH-NSK-2024-8842 (पासवर्ड: कोई भी 4+ अक्षर)",
    orUseOtp: "त्वरित एसएमएस ओटीपी से लॉग इन",
    sendOtp: "फोन पर ओटीपी भेजें",
    completeProfileTitle: "किसान पंजीकरण एवं प्रोफ़ाइल",
    completeProfileSubtitle: "अपने उपज लेजर को देखने के लिए अपने आधिकारिक एफपीओ सदस्य विवरण पूर्ण करें।",
    fullName: "किसान का पूरा नाम",
    fullNamePlaceholder: "उदा. रमेश बाबूराव पाटिल",
    memberId: "किसान सदस्य आईडी",
    memberIdPlaceholder: "उदा. MH-NSK-2024-8842",
    phoneNumber: "पंजीकृत मोबाइल नंबर",
    fpoName: "संबद्ध एफपीओ का नाम",
    preferredLang: "पसंदीदा भाषा",
    village: "गाँव / ग्राम पंचायत",
    villagePlaceholder: "उदा. ओझर मिग",
    district: "ज़िला / तहसील",
    districtPlaceholder: "उदा. नासिक, निफाड़",
    primaryCrop: "मुख्य आपूर्ति फसल",
    saveProfileBtn: "प्रोफ़ाइल पूर्ण करें और डैशबोर्ड खोलें",
    totalProduceSold: "कुल उपज बिक्री",
    totalNetAmount: "कुल शुद्ध राशि",
    gradeWiseWeight: "ग्रेड अनुसार विवरण",
    gradeA: "ग्रेड अ (सुपर)",
    gradeB: "ग्रेड ब (मानक)",
    gradeC: "ग्रेड स (सामान्य)",
    gradeADesc: "प्रीमियम — सबसे कम नमी और अशुद्धियाँ",
    gradeBDesc: "खरीद मानकों के सर्वथा अनुरूप",
    gradeCDesc: "मानक से कम — रियायती मूल्य",
    myProduce: "मेरी उपज का विवरण",
    soldKg: "बेची गई मात्रा",
    earnings: "शुद्ध कमाई",
    transactionsHeading: "लेन-देन का इतिहास",
    searchPlaceholder: "लेन-देन आईडी खोजें (उदा. TXN-8092)...",
    filterProduct: "उत्पाद / फसल",
    filterGrade: "गुणवत्ता ग्रेड",
    filterDate: "समय अवधि",
    sortBy: "क्रमबद्ध करें",
    all: "सभी",
    thisMonth: "इस महीने",
    lastMonth: "पिछले महीने",
    sortNewest: "सबसे नया पहले",
    sortOldest: "सबसे पुराना पहले",
    sortHighWeight: "सर्वाधिक वजन",
    sortLowWeight: "न्यूनतम वजन",
    sortHighAmount: "सर्वाधिक राशि",
    statusConfirmed: "सत्यापित",
    statusPending: "पुष्टि की प्रतीक्षा",
    statusIssue: "समस्या दर्ज है",
    statusLocked: "लॉक / सुरक्षित",
    grossWeight: "सकल वजन",
    tareWeight: "बोरी/खाली वजन",
    netWeight: "शुद्ध वजन",
    ratePerKg: "भाव / कि.ग्रा.",
    amount: "कुल राशि",
    station: "संग्रहण केंद्र",
    operator: "ऑपरेटर आईडी",
    raiseIssue: "समस्या दर्ज करें",
    confirmDelivery: "डिलीवरी सत्यापित करें",
    viewDetails: "विवरण देखें",
    consignmentPhoto: "कंसाइनमेंट फोटो",
    tamperEvident: "कांटे पर ली गई छेड़छाड़-रोधी फोटो",
    photoUnavailable: "कंसाइनमेंट फोटो उपलब्ध नहीं है",
    raiseIssueModalTitle: "एफपीओ को समस्या दर्ज करें",
    raiseIssueModalSubtitle: "अपनी आपत्ति दर्ज करें। ऑपरेटर का मूल रिकॉर्ड सुरक्षित और अपरिवर्तित रहेगा।",
    issueType: "समस्या का प्रकार",
    selectIssueType: "-- समस्या का प्रकार चुनें --",
    issueTypeWeight: "गलत वजन दर्ज हुआ",
    issueTypeGrade: "गलत गुणवत्ता ग्रेड",
    issueTypeAmount: "गलत दर या भुगतान राशि",
    issueTypeProduct: "गलत फसल दर्ज हुई",
    issueTypePhoto: "कंसाइनमेंट फोटो में त्रुटि",
    issueTypeOther: "अन्य समस्या",
    issueDesc: "समस्या का विस्तार से विवरण दें",
    issueDescPlaceholder: "कांटे और खरीद केंद्र पर हुई गलती का विवरण यहाँ लिखें...",
    submitIssueBtn: "समस्या एफपीओ को जमा करें",
    issueSubmittedSuccess: "आपकी समस्या एफपीओ समीक्षा के लिए दर्ज कर दी गई है।",
    otpModalTitle: "किसान डिलीवरी पुष्टि (ओटीपी)",
    otpModalSubtitle: "अपने पंजीकृत फोन पर भेजा गया सत्यापन ओटीपी दर्ज करें",
    otpInstruction: "4-अंकीय ओटीपी दर्ज करें",
    verifyAndLockBtn: "ओटीपी सत्यापित करें एवं लेन-देन लॉक करें",
    otpSimulatedBanner: "फोन पर प्राप्त हुआ एसएमएस",
    otpCodeLabel: "आपका सत्यापन ओटीपी कोड है:",
    otpSuccessMsg: "लेन-देन सफलतापूर्वक सत्यापित हो गया! रिकॉर्ड अब स्थायी रूप से लॉक है।",
    lockedExplanation: "यह लेन-देन स्थायी रूप से लॉक है। किसी भी त्रुटि के लिए समस्या दर्ज करें।",
    cancel: "रद्द करें",
    close: "बंद करें",
    printSlip: "पर्ची प्रिंट / सुरक्षित करें",
    noTransactionsFound: "आपके द्वारा चुने गए फिल्टर के अनुसार कोई लेन-देन नहीं मिला।"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('kisan_lang') || 'en';
  });

  const toggleLanguage = () => {
    const next = lang === 'en' ? 'hi' : 'en';
    setLang(next);
    localStorage.setItem('kisan_lang', next);
  };

  const setLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('kisan_lang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
